Repository prgrms-be-devcourse/NBE-4-5-2-Team05, pull requests merged in 2025-03, with the labels that each got.

#36 옥정현/feat 31 User api 구현 및 jwt 적용
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/NBE_4_5_2/Team5/Team5Application.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/controller/UserController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/LoginUserDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/LoginUserForm.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/RefreshUserForm.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/SignUpUserForm.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/UserDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/entity/User.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/repository/UserRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/AuthTokenService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/UserService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/UserValidator.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/Rq.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/app/AppConfig.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/aspect/ResponseAspect.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/dto/Empty.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/dto/PageDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/dto/RsData.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/entity/BaseEntity.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/entity/BaseTime.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/exception/ServiceException.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/init/BaseInitData.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CustomAuthenticationFilter.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/SecurityConfig.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/SecurityUser.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/standard/util/Ut.java
  backend/src/test/java/com/NBE_4_5_2/Team5/Team5ApplicationTests.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/controller/UserControllerTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/service/AuthTokenServiceTest.java
Labels: feature

#45 [feat] 최근 본 상품 추가 구현
  backend/build.gradle
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/controller/ProductPostController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/dto/response/PreviewPostResponse.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/dto/response/ProductPostResponse.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/repository/ProductPostRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/service/ProductPostService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/service/RecentlyViewedService.java
Labels: feature

#33 페이머니 충전 결제 및 상품으로 페이머니 결제 서비스 구현
  backend/.gitignore
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/controller/PaymentController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/dto/PaymentChargeReqBody.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/dto/PaymentDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/dto/PaymentMetaData.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/entity/Payment.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/enums/PaymentStatus.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/repository/PaymentRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/service/PaymentProviderAdapter.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/service/PaymentService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/entity/ProductPost.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/controller/UserController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/entity/User.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/UserService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/aspect/ResponseAspect.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/exception/ServiceException.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/exception/TossPaymentException.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/exception/payment/InsufficientPayMoneyException.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/exception/product/ProductNotFoundException.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/filter/CorsFilter.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/init/BaseInitData.java
  backend/src/main/java/com/NBE_4_5_2/Team5/infrastructure/TossPaymentProviderAdapter.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/payment/entity/PaymentTest.java
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.mjs
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.mjs
  frontend/public/file.svg
  frontend/public/globe.svg
  frontend/public/next.svg
  frontend/public/vercel.svg
  frontend/public/window.svg
  frontend/src/app/favicon.ico
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/payment/CheckoutButton.tsx
  frontend/src/app/payment/ClientPage.tsx
  frontend/src/app/payment/page.tsx
  frontend/src/app/success/clientPage.tsx
  frontend/src/app/success/page.tsx
  frontend/src/middleware.ts
  frontend/tsconfig.json
Labels: feature

#37 김아성/feat 2 상품 게시글 및 카테고리 구현
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/category/controller/CategoryController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/category/entity/Category.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/category/repository/CategoryRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/category/service/CategoryService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/controller/ProductPostController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/dto/response/PreviewPostResponse.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/entity/ProductCategory.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/entity/ProductPost.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/repository/ProductPostRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/service/ProductPostService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/service/RecentlyViewedService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/init/BaseInitData.java
Labels: feature

#40 서준식/feat 8
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/UserDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/UserUpdateRequest.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/repository/UserRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/SecurityConfig.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/controller/UserControllerTest.java
Labels: feature

#56 [feat] OAuth2 로그인 구현
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/controller/UserController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/entity/User.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/Rq.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CorsConfig.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CustomAuthenticationSuccessHandler.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CustomAuthorizationRequestResolver.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CustomOAuth2UserService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/SecurityConfig.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/SecurityUser.java
  backend/src/main/resources/application-secret.yml
  backend/src/main/resources/application-secret.yml.default
  backend/src/main/resources/application.yml
  frontend/src/app/page.tsx
Labels: feature

#62 fix: 누락된 코드 추가
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/service/ProductPostService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/entity/User.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/controller/UserControllerTest.java
Labels: fix

#57 옥정현/feat 51 accessToken에 Role 정보 추가 및 리펙토링
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/category/controller/CategoryController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/controller/ProductPostController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/controller/UserController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/LoginUserDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/LoginUserForm.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/RefreshUserForm.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/SignUpUserForm.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/UserDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/entity/Role.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/entity/User.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/AuthTokenService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/UserService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/Rq.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/init/BaseInitData.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CustomAuthenticationFilter.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CustomOAuth2UserService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/SecurityConfig.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/SecurityUser.java
  backend/src/test/java/com/NBE_4_5_2/Team5/api/TestErrorController.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/post/post/controller/ProductPostControllerTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/controller/UserControllerTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/service/AuthTokenServiceTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/global/security/CustomAuthenticationFilterTest.java
Labels: feature, fix

#58 깃허브 액션으로 테스트 자동화
  .github/workflows/gradle.yml
  backend/.gitignore
  backend/src/test/java/com/NBE_4_5_2/Team5/resources/application-secret.yml
  backend/src/test/java/com/NBE_4_5_2/Team5/resources/application-test.yml
  backend/src/test/java/com/NBE_4_5_2/Team5/resources/application.yml
Labels: chore

#64 Revert "깃허브 액션으로 테스트 자동화"
  .github/workflows/gradle.yml
  backend/.gitignore
  backend/src/test/java/com/NBE_4_5_2/Team5/resources/application-secret.yml
  backend/src/test/java/com/NBE_4_5_2/Team5/resources/application-test.yml
  backend/src/test/java/com/NBE_4_5_2/Team5/resources/application.yml
Labels: fix

#47 관리자 게시글 삭제
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/admin/controller/AdminController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/admin/dto/AdminResBody.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/admin/dto/NoticeResBody.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/admin/entity/NoticePost.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/admin/repository/NoticePostRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/admin/service/AdminService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/controller/PaymentController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/category/entity/Category.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/category/repository/CategoryRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/category/service/CategoryService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/dto/request/ProductPostModifyForm.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/dto/request/ProductPostWriteForm.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/dto/response/PreviewPostResponse.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/dto/response/ProductPostResponse.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/entity/LikedPost.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/entity/ProductCategory.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/entity/ProductPost.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/enums/ProductStatus.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/repository/LikedPostRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/repository/ProductCategoryRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/repository/ProductPostRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/service/RecentlyViewedService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/UserDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/entity/User.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/repository/UserRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/AuthTokenService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/UserService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/entity/BaseTime.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/exception/ServiceException.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/response/Empty.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/response/PageDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/response/RsData.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/NBE_4_5_2/Team5/TestConfig.java
  backend/src/test/java/com/NBE_4_5_2/Team5/Util.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/admin/controller/AdminControllerTest.java
  backend/src/test/resources/application-test.yml
Labels: feature

#39 관리자 유저 정지
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/NBE_4_5_2/Team5/batch/BanListBatchScheduler.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/admin/controller/AdminController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/admin/dto/BanListDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/admin/dto/BanResBody.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/admin/entity/BanList.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/admin/repository/BanListRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/admin/service/AdminService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/entity/ProductPost.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/UserDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/entity/User.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/repository/UserRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/UserService.java
  backend/src/main/resources/application-secret.yml
  backend/src/main/resources/application-secret.yml.default
  backend/src/main/resources/application-test.yml
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/admin/controller/AdminControllerTest.java
  backend/src/test/java/config/TestConfig.java
  backend/src/test/java/util/Util.java
  backend/src/test/resources/application-test.yml
  backend/src/test/resources/junit-platform.properties
Labels: feature

#38 관리자 공지사항 등록
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/UserDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/entity/User.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/UserService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/Rq.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/SecurityUser.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/NBE_4_5_2/Team5/Util.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/admin/controller/AdminControllerTest.java
Labels: feature

#54 fix: ProductPost의 상품 구매 삭제
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/controller/ProductPostController.java
Labels: enhancement

#48 댓글 작성
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/comment/controller/PostCommentController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/comment/dto/CommentDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/comment/entity/Comment.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/comment/repository/CommentRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/comment/service/CommentService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/entity/ProductPost.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/repository/ProductPostRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/entity/User.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/post/comment/controller/PostCommentControllerTest.java
Labels: feature

#71 옥정현/feat 59 refreshToken을 redis에 저장하고 로그인 할 때 발급하도록 변경
  .github/workflows/main.yml
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/admin/service/AdminService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/controller/UserController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/dto/AuthToken.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/entity/RefreshToken.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/entity/User.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/repository/RedisRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/repository/UserRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/AuthTokenService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/RedisService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/UserService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/Rq.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/config/RedisConfig.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CustomAuthenticationFilter.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CustomAuthenticationSuccessHandler.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/standard/util/Ut.java
  backend/src/main/resources/application-secret.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/NBE_4_5_2/Team5/Team5ApplicationTests.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/admin/controller/AdminControllerTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/post/comment/controller/PostCommentControllerTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/post/post/controller/ProductPostControllerTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/controller/UserControllerTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/repository/RedisContainersTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/service/AuthTokenServiceTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/global/config/RedisTestContainerConfig.java
  backend/src/test/java/com/NBE_4_5_2/Team5/global/security/CustomAuthenticationFilterTest.java
Labels: feature, fix

#34 윤원석/feat/#9 채팅방 생성, 메세지 전송
  .github/workflows/main.yml
  .idea/.gitignore
  .idea/NBE-4-5-2-Team05-develop.iml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/jsLibraryMappings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/Team5.main.iml
  .idea/modules/Team5.test.iml
  .idea/vcs.xml
  backend/build.gradle
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/chat/controller/ChatController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/chat/controller/ChatRoomController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/chat/controller/LoginController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/chat/dto/ChatRoomDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/chat/dto/MessageDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/chat/entity/AccessProvider.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/chat/entity/ChatMessage.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/chat/entity/ChatRoom.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/chat/repository/MessageRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/chat/service/ChatRoomService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/chat/service/ChatService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/entity/User.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/AuthTokenService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/app/AppConfig.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/config/HttpHandshakeInterceptor.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/config/RedisConfig.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/config/WebSocketConfig.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/handler/StompHandler.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/redis/RedisSubscriber.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/s3/S3Config.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/s3/S3Controller.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/s3/S3UploadService.java
  backend/src/main/resources/application-secret.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/templates/chat/room.html
  backend/src/main/resources/templates/chat/roomdetail.html
  backend/src/main/resources/templates/login/login.html
  backend/src/test/resources/application-secret.yml
  backend/src/test/resources/application-test.yml
Labels: feature

#88 옥정현/fix 87 refresh api 로직 수정
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/controller/UserController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/service/UserService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CustomAuthenticationFilter.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/controller/UserControllerTest.java
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: fix

#70 [BE] chore : 백엔드 서버 배포
  backend/.gitignore
  backend/Jenkinsfile
  backend/appspec.yml
  backend/build.gradle
  backend/gradle.properties
  backend/jenkinsfile
  backend/scripts/start_app.sh
  backend/src/main/java/com/NBE_4_5_2/Team5/Team5Application.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CustomAuthenticationFilter.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-monitor.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
Labels: chore

#93 관리자 공지사항, 사용자 관리, 상품 삭제 구현
  .gitignore
  backend/build.gradle
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/admin/controller/AdminController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/admin/dto/NoticeResBody.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/admin/entity/NoticePost.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/admin/repository/BanListRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/admin/service/AdminService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/repository/UserRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/exception/notice/NoticeException.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/exception/notice/NoticeNotFoundException.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/init/BaseInitData.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/admin/controller/AdminControllerTest.java
  frontend/.gitignore
  frontend/package.json
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/_type/NoticeListItem.ts
  frontend/src/app/_type/ProductListItem.ts
  frontend/src/app/_type/UserListItem.ts
  frontend/src/app/admin/_components/common/PageSizeSelector.tsx
  frontend/src/app/admin/_components/common/Pagination.tsx
  frontend/src/app/admin/_components/productlist/ProductListAccordian.tsx
  frontend/src/app/admin/_components/userlist/UserListAccordian.tsx
  frontend/src/app/admin/_pages/NoticeAdmin.tsx
  frontend/src/app/admin/_pages/NoticeForm.tsx
  frontend/src/app/admin/_pages/NoticeListAccordian.tsx
  frontend/src/app/admin/_pages/ProductListAdmin.tsx
  frontend/src/app/admin/_pages/SystemLog.tsx
  frontend/src/app/admin/_pages/UserListAdmin.tsx
  frontend/src/app/admin/page.tsx
  frontend/src/components/ui/breadcrumb.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/card.tsx
  frontend/src/components/ui/input.tsx
  frontend/src/components/ui/label.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/components/ui/tabs.tsx
  frontend/src/components/ui/textarea.tsx
Labels: feature

#95 swagger ui API docs 작성
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/chat/controller/ChatRoomController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/controller/PaymentController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/category/controller/CategoryController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/comment/controller/PostCommentController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/controller/ProductPostController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/dto/request/ProductPostModifyForm.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/dto/request/ProductPostWriteForm.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/admin/controller/AdminController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/s3/S3Config.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/s3/S3Controller.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/s3/S3UploadService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CustomAuthenticationFilter.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/springDocs/SpringDocConfig.java
  backend/src/main/java/com/NBE_4_5_2/Team5/infrastructure/s3/S3Config.java
  backend/src/main/java/com/NBE_4_5_2/Team5/infrastructure/s3/S3Controller.java
  backend/src/main/java/com/NBE_4_5_2/Team5/infrastructure/s3/S3UploadService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/infrastructure/toss/TossPaymentProviderAdapter.java
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: feature

#86 [BE,FE] 내 상품 관리 페이지 구현 완료
  backend/application.pid
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/controller/ProductPostController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/dto/response/PreviewPostResponse.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/repository/LikedPostRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/repository/ProductPostRepository.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/service/ProductPostService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/app/AppConfig.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/init/BaseInitData.java
  backend/src/main/resources/application-secret.yml
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/admin/controller/AdminControllerTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/user/controller/UserControllerTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/user/repository/RedisContainersTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/user/service/AuthTokenServiceTest.java
  frontend/package-lock.json
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/stores/auth/loginMemberStore.tsx
  frontend/src/app/user/login/ClientPage.tsx
  frontend/src/app/user/login/page.tsx
  frontend/src/app/user/me/ClientPage.tsx
  frontend/src/app/user/me/layout.tsx
  frontend/src/app/user/me/modify/ClientPage.tsx
  frontend/src/app/user/me/modify/page.tsx
  frontend/src/app/user/me/page.tsx
  frontend/src/app/user/me/purchase/history/ClientPage.tsx
  frontend/src/app/user/me/purchase/history/page.tsx
  frontend/src/app/user/me/purchase/wishlist/ClientPage.tsx
  frontend/src/app/user/me/purchase/wishlist/page.tsx
  frontend/src/app/user/me/sell/history/ClientPage.tsx
  frontend/src/app/user/me/sell/history/page.tsx
  frontend/src/app/user/me/sell/manage/ClientPage.tsx
  frontend/src/app/user/me/sell/manage/page.tsx
  frontend/src/app/user/me/sell/shipping/ClientPage.tsx
  frontend/src/app/user/me/sell/shipping/page.tsx
  frontend/src/components/auth/RequireAdmin.tsx
  frontend/src/components/auth/RequireAnonymous.tsx
  frontend/src/components/auth/RequireAuthenticated.tsx
  frontend/src/components/ui/table.tsx
  frontend/src/middleware.ts
Labels: feature

#101 결제 프런트엔드 페이지 작성
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/controller/PaymentController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/service/PaymentService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/entity/ProductPost.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/user/dto/UserDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/user/entity/User.java
  backend/src/main/resources/static/paymentOptions.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/payment/ClientPage.tsx
  frontend/src/app/payments/CheckoutButton.tsx
  frontend/src/app/payments/ClientPage.tsx
  frontend/src/app/payments/RadioBtns.tsx
  frontend/src/app/payments/page.tsx
  frontend/src/app/posts/[postId]/page.tsx
  frontend/src/app/success/clientPage.tsx
  frontend/src/app/user/login/ClientPage.tsx
  frontend/src/components/ui/radio-group.tsx
  frontend/src/lib/client.tsx
Labels: feature

#97 프론트엔드 배포
  .gitignore
  backend/src/main/java/com/NBE_4_5_2/Team5/global/filter/CorsFilter.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CorsConfig.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application-secret.yml
  backend/src/test/resources/application-test.yml
  frontend/appspec.yml
  frontend/scripts/start_app.sh
  frontend/src/app/ClientLayout.tsx
  frontend/src/app/payment/ClientPage.tsx
  frontend/src/app/payments/CheckoutButton.tsx
  frontend/src/app/posts/[postId]/page.tsx
  frontend/src/app/posts/new/page.tsx
  frontend/src/app/posts/page.tsx
  frontend/src/app/success/clientPage.tsx
  frontend/src/app/success/page.tsx
  frontend/src/app/user/me/modify/ClientPage.tsx
  frontend/src/app/user/me/sell/history/page.tsx
  frontend/src/app/user/signup/ClientPage.tsx
  frontend/src/app/util/auth.ts
  frontend/src/lib/backend/apiV1/schema.d.ts
  frontend/src/middleware.ts
Labels: feature

#107 fix: 카카오 로그인 이메일 인증 성공하도록 수정
  backend/.gitignore
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/controller/ProductPostController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/entity/ProductPost.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/security/CustomOAuth2UserService.java
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: fix

#110 옥정현/refactor 101 entity Stirng id 초기화 방식 통일, testContainer에서 redis 중복 생성되던거 수정
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/base/entity/BaseEntity.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/base/entity/BaseLongIdEntity.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/base/entity/BaseTime.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/entity/Payment.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/payment/service/PaymentService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/category/entity/Category.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/comment/entity/Comment.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/comment/service/CommentService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/entity/LikedPost.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/entity/ProductCategory.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/entity/ProductPost.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/post/post/service/ProductPostService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/admin/entity/NoticePost.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/admin/service/AdminService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/user/entity/User.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/user/service/UserService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/init/BaseInitData.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/post/comment/controller/PostCommentControllerTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/post/post/controller/ProductPostControllerTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/admin/controller/AdminControllerTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/user/controller/UserControllerTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/user/repository/RedisContainersTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/user/service/AuthTokenServiceTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/user/service/email/service/BouncedEmailServiceTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/domain/user/user/service/email/service/EmailServiceTest.java
  backend/src/test/java/com/NBE_4_5_2/Team5/global/config/RedisTestContainerConfig.java
  backend/src/test/java/com/NBE_4_5_2/Team5/global/config/TestConfig.java
  backend/src/test/java/com/NBE_4_5_2/Team5/global/security/CustomAuthenticationFilterTest.java
Labels: refactoring, fix

#113 Hotfix : 관리자 화면 레이아웃 조정
  frontend/src/app/admin/ClientPage.tsx
  frontend/src/app/admin/_pages/ProductListAdmin.tsx
  frontend/src/app/admin/_pages/UserListAdmin.tsx
  frontend/src/app/payment/ClientPage.tsx
  frontend/src/app/posts/[postId]/page.tsx
  frontend/src/components/posts/RecentlyUploadedSection.tsx
  frontend/src/components/posts/RecentlyViewedSection.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: fix

#114 Hotfix : axios 호출 구현 삭제
  frontend/src/app/posts/[postId]/page.tsx
  frontend/src/components/posts/RecentlyUploadedSection.tsx
  frontend/src/components/posts/RecentlyViewedSection.tsx
Labels: fix

#116 fix: 쿠키 설정 변경
  backend/src/main/java/com/NBE_4_5_2/Team5/global/Rq.java
Labels: fix

#128 comment 구현
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/admin/controller/AdminController.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/admin/dto/NoticeDto.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/admin/dto/NoticeResBody.java
  backend/src/main/java/com/NBE_4_5_2/Team5/domain/user/admin/service/AdminService.java
  backend/src/main/java/com/NBE_4_5_2/Team5/global/exception/notice/NoticeNotFoundException.java
  frontend/src/app/posts/[postId]/_pages/comments.tsx
  frontend/src/app/posts/notices/[noticeId]/page.tsx
  frontend/src/app/posts/page.tsx
  frontend/src/lib/backend/apiV1/schema.d.ts
Labels: feature
